version: 2
updates:
  - package-ecosystem: gradle
    directories:
      - '**/*'
    schedule:
      interval: weekly
      day: sunday
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
    open-pull-requests-limit: 10
    labels:
      - 'type: dependency-upgrade'
    groups:
      development-dependencies:
        update-types:
          - patch
        patterns:
          - com.github.spotbugs
          - io.spring.*
          - com.icegreen:greenmail
          - org.mock-server*
          - org.apache.curator*
          - com.squareup.okhttp3*

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: saturday
    labels:
      - 'type: task'
    groups:
      development-dependencies:
        patterns:
          - '*'